name: Emergency Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
        restore-keys: gradle-${{ runner.os }}-
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Clean project
      run: ./gradlew clean
      
    - name: Build debug APK
      run: ./gradlew assembleDebug --no-daemon --stacktrace --info
      
    - name: List APK files
      run: find . -name "*.apk" -type f
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: emergency-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30